package com.aryutalks.Models;

public class Post {
    private String heading;
    private String content;
    private String imageUrl;
    private String timestamp;
    private String hashtag;

    public Post() {
    }

    public Post(String heading, String content, String imageUrl, String timestamp, String hashtag) {
        this.heading = heading;
        this.content = content;
        this.imageUrl = imageUrl;
        this.timestamp = timestamp;
        this.hashtag = hashtag;
    }

    // Getters and setters
    // Note: Generated by IDE or manually similar to previous ones
}
